
[eww.files]
eww = "~/.config/eww"

[waybar.files]
waybar = "~/.config/waybar"

[alacritty.files]
alacritty = "~/.config/alacritty"

[foot.files]
foot = "~/.config/foot"

[ghostty.files]
ghostty = "~/.config/ghostty"

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[fastfetch.files]
"fastfetch.jsonc" = "~/.config/fastfetch/config.jsonc"

[bash.files]
bashrc = "~/.bashrc"

[zsh.files]
zshenv = "~/.zshenv"
zshrc = "~/.zshrc"

[mime.files]
"mimeapps.list" = "~/.config/mimeapps.list"

[yazi.files]
yazi = "~/.config/yazi"

[nvim.files]
nvim = "~/.config/nvim"

[walker.files]
walker = "~/.config/walker"

[tiny.files]
tiny = "~/.config/tiny"
