[niri.files]
niri = "~/.config/niri"

[quickshell.files]
quickshell = "~/.config/quickshell"

[waybar.files]
waybar = "~/.config/waybar"

[foot.files]
foot = "~/.config/foot"

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[fastfetch.files]
"fastfetch.jsonc" = "~/.config/fastfetch/config.jsonc"

[bash.files]
bash_profile = "~/.bash_profile"
bashrc = "~/.bashrc"

[zsh.files]
zshenv = "~/.zshenv"
zshrc = "~/.zshrc"

[yazi.files]
yazi = "~/.config/yazi"

[nvim.files]
nvim = "~/.config/nvim"

[tiny.files]
tiny = "~/.config/tiny"
