[niri.files]
niri = "~/.config/niri"

[foot.files]
foot = "~/.config/foot"

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[bash.files]
bash_profile = "~/.bash_profile"
bashrc = "~/.bashrc"

[zsh.files]
zshenv = "~/.zshenv"
zshrc = "~/.zshrc"

[btop.files]
btop = "~/.config/btop"

[fastfetch.files]
"fastfetch.jsonc" = "~/.config/fastfetch/config.jsonc"

[yazi.files]
yazi = "~/.config/yazi"

[helix.files]
helix = "~/.config/helix"

[tiny.files]
tiny = "~/.config/tiny"
